# Generated by Django 5.1.7 on 2025-04-17 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date_issued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
