# Generated by Django 5.1.7 on 2025-04-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_receipt_date_issued'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesReport',
        ),
    ]
