# Generated by Django 5.1.7 on 2025-05-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
