from django.urls import path
from .views import (
    landing_page, user_login, register, user_logout, dashboard, admin_dashboard,
    record_attendance, submit_leave_request, leave_list, approve_leave, reject_leave,
    view_payroll, generate_payroll, view_payrate, holiday_list, department_list,
    add_position, update_position, delete_position, position_list, update_position,
    employee_list, employee_detail, add_department, delete_department,update_holiday, add_holiday, delete_holiday,
)

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('login/', user_login, name='login'),
    path('register/', register, name='register'),
    path('logout/', user_logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
    path('attendance/', record_attendance, name='attendance'),
    path('leave-request/', submit_leave_request, name='leave_request'),
    path('leave_list/', leave_list, name='leave_list'),
    path('leave/approve/<int:leave_id>/', approve_leave, name='approve_leave'),
    path('leave/reject/<int:leave_id>/', reject_leave, name='reject_leave'),
    path('payroll/', view_payroll, name='view_payroll'),
    path('generate-payroll/', generate_payroll, name='generate_payroll'),
    path('payrate/', view_payrate, name='view_payrate'),
    path('holidays/', holiday_list, name='holiday_list'),
    path('holidays/add/', add_holiday, name='add_holiday'),
    path('holidays/update/<int:pk>/',update_holiday, name='update_holiday'),
    path('holidays/delete/<int:pk>/', delete_holiday, name='delete_holiday'),
    path('departments/', department_list, name='department_list'),
    path('departments/add/', add_department, name='add_department'),
    path('departments/delete/<int:department_id>/', delete_department, name='delete_department'),
    path('positions/', position_list, name='position_list'),
    path('positions/add/', add_position, name='add_position'),
    path('positions/edit/<int:position_id>/', update_position, name='update_position'),
    path('positions/update/<int:position_id>/', update_position, name='update_position'),
    path('positions/delete/<int:position_id>/', delete_position, name='delete_position'),
    path('employees/', employee_list, name='employee_list'),
    path('employee/<int:id>/', employee_detail, name='employee_detail'),
]
