# Generated by Django 5.1.4 on 2025-05-01 22:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_is_confirmed_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note attached to the order or payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Upload image of the payment receipt', null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Awaiting Confirmation', 'Awaiting Confirmation'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the order', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
