# Generated by Django 5.1.5 on 2025-04-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_reservation_payment_status_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='freebies',
            field=models.CharField(choices=[('dindugan', 'Dindugan'), ('paklay', 'Paklay'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
