# Generated by Django 5.1.5 on 2025-04-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_reservation_freebies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='freebies',
        ),
    ]
