# Generated by Django 5.1.5 on 2025-04-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_remove_reservation_freebies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='delivery_option',
            field=models.CharField(choices=[('pickup', 'Pick-up'), ('door', 'Door-to-Door')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='package_deal',
            field=models.CharField(choices=[('paklay', 'Paklay'), ('dinuguan', 'Dinuguan'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
