# Generated by Django 5.1.5 on 2025-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
