# Generated by Django 5.1.5 on 2025-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_reservation_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gcash_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gcash_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
