# Generated by Django 5.1.7 on 2025-04-23 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_alter_order_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 23, 14, 44, 15, 899020, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
