# Generated by Django 5.1.4 on 2025-04-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_customer_address_order_customer_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this product from the storefront'),
        ),
    ]
