# Generated by Django 5.1.4 on 2025-04-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this product from shoppers'),
        ),
    ]
