# Generated by Django 5.1.4 on 2025-04-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_status_alter_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(help_text='Upload proof of payment (receipt image)', upload_to='receipts/'),
        ),
    ]
