# Generated by Django 5.1.4 on 2025-04-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_status_alter_payment_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'default_permissions': ('add', 'change', 'view')},
        ),
    ]
