# Generated by Django 5.1.4 on 2025-04-30 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(upload_to='receipts/'),
        ),
    ]
