# Generated by Django 5.2 on 2025-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_reference_number_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Iligan2L Hardware', max_length=100)),
                ('address', models.TextField(default='123 Main Street, Iligan City, Philippines')),
                ('phone', models.CharField(default='+63 912 345 6789', max_length=20)),
                ('email', models.EmailField(default='info@iligan2l.com', max_length=254)),
            ],
        ),
    ]
