# Generated by Django 5.2 on 2025-05-06 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_restock_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
